# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 740d4cbd718f7077670a56c5ad49391b4a63cedce089d5251681ae1a723145ade18ce7c7418d1c7c2aa73c8464541ac3b5ca806043d330e453967c299737060d

test:
  secret_key_base: 82e2cc7e57882e23bc3d31ac5e083c301f1b12256e5a8520caa9c1ca375a3c5b696d476d4228f900adb2bf78716d8c8b404e59538ad5907667432a6602d923c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
